version: '3.1'

services:
  db-postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: